var carName="volvo";
var number=50;
var x=5;
var y=10;
var z=x+y;
var person={firstName:"John",lastName:"Doe",age:35};
console.log(carName);
console.log(number);
console.log("Volvo");
console.log(z);
console.log(x+y);
console.log(person.firstName+" "+ person.lastName + " is " +person.age);
console.log(Object.keys(person));
console.log(Object.getPropertyByown(person));